# Generated by Django 2.2.18 on 2021-02-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'e-mail template', 'verbose_name_plural': 'e-mail templates'},
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='locale',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=3, choices=[(1, '1. Critical'), (2, '2. High'), (3, '3. Medium'), (4, '4. Low')], default=3, help_text='1 = Highest Priority, 5 = Low Priority', verbose_name='Priority'),
        ),
    ]
