# Generated by Django 2.2.18 on 2021-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210223_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=3, choices=[(1, '1. Critical'), (2, '2. High'), (3, '3. Medium'), (4, '4. Low')], default=3, help_text='1 = Highest Priority, 4 = Low Priority', verbose_name='Priority'),
        ),
    ]
