# Generated by Django 2.2.18 on 2021-02-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210223_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketcustomfieldvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ticketcustomfieldvalue',
            name='field',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfieldvalue',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='TicketCustomFieldValue',
        ),
    ]
